##############################################################################################################
# +--------------------------------------------------------------------------------------------------------+ #
# | __          __  _______ _____ _    _ _____   ____   _____   _____  ______ _____   ____  _____ _______  | #
# | \ \        / /\|__   __/ ____| |  | |  __ \ / __ \ / ____| |  __ \|  ____|  __ \ / __ \|  __ \__   __| | #
# |  \ \  /\  / /  \  | | | |    | |__| | |  | | |  | | |  __  | |__) | |__  | |__) | |  | | |__) | | |    | #
# |   \ \/  \/ / /\ \ | | | |    |  __  | |  | | |  | | | |_ | |  _  /|  __| |  ___/| |  | |  _  /  | |    | #
# |    \  /\  / ____ \| | | |____| |  | | |__| | |__| | |__| | | | \ \| |____| |    | |__| | | \ \  | |    | #
# |     \/  \/_/    \_\_|  \_____|_|  |_|_____/ \____/ \_____| |_|  \_\______|_|     \____/|_|  \_\ |_|    | #
# |                                                                                                        | #
# +--------------------------------------------------------------------------------------------------------+ #
##############################################################################################################

name: WatchdogReport
version: 1.1.0
main: me.itzsomebody.watchdogreport.WatchdogReport
author: ItzSomebody
description: Watchdog report
depend: [Watchdog]

commands:
    watchdogreport:
        aliases: [wdr]
        description: Base command